name: Create Docker Image

on:
  push:
    branches:
    - main
    - master
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main
    - master
    paths-ignore:
    - '**.md'
  schedule:
    - cron: "3 4 * * *"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
        - { version: "edge", tag: "alpine-edge" }
        - { version: "latest", tag: "latest" }
        - { version: "latest", tag: "alpine-latest" }
        - { version: "3.15", tag: "alpine-3.15" }
        - { version: "3.15.0", tag: "alpine-3.15.0" }
        - { version: "3.14", tag: "alpine-3.14" }
        - { version: "3.14.3", tag: "alpine-3.14.3" }
        - { version: "3.14.2", tag: "alpine-3.14.2" }
        - { version: "3.13", tag: "alpine-3.13" }
        - { version: "3.13.7", tag: "alpine-3.13.7" }
        - { version: "3.13.6", tag: "alpine-3.13.6" }
        - { version: "3.12", tag: "alpine-3.12" }
        - { version: "3.12.9", tag: "alpine-3.12.9" }
        - { version: "3.12.8", tag: "alpine-3.12.8" }
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup qemu
      uses: docker/setup-qemu-action@v1
    - name: setup buildx
      uses: docker/setup-buildx-action@v1
    - name: cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache-${{ matrix.build.tag }}
        key: ${{ runner.os }}-buildx-${{ matrix.build.tag }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.build.tag }}-
          ${{ runner.os }}-buildx-
    - name: login dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        tags: jipp13/fritzcollectd:${{ matrix.build.tag }}
        cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.build.tag }}
        cache-to: type=local,dest=/tmp/.buildx-cache-${{ matrix.build.tag }}
        build-args: |
          version=${{ matrix.build.version }}
